version: "3.8"
x-env-aliases:
  - &DEFAULT_BUILD_ARGS
    PHP_TAG: "${PHP_VERSION:-8.0}-cli-alpine${ALPINE_VERSION:-3.16}"
    PHP_API_VERSION: "${PHP_API_VERSION:-20200930}"
    COMPOSER_ARGS: "${COMPOSER_ARGS:-install}"
    COMPOSER_AUTH: "${COMPOSER_AUTH:-}"
    SWOOLE_EXTENSION: "${SWOOLE_EXTENSION:-openswoole}"
    SWOOLE_VERSION: "${SWOOLE_VERSION:-4.12.1}"
    COMPOSER_TAG: "${COMPOSER_TAG:-2.5.2}"
    XDEBUG_TAG: "${XDEBUG_TAG:-3.2.0}"

volumes:
  coverage: {}

services:
  releaser:
    image: "docker.io/openswoolebundle/release-version-script:0.4.1"
    environment:
      DEBUG: "${DEBUG:-0}"
      DRY_RUN: "${DRY_RUN:-1}"
      GH_REPOSITORY: "${GH_REPOSITORY:-openswoole-bundle/openswoole-bundle}"
      GH_COMMITER_NAME: "${GH_COMMITER_NAME:-openswoole-bundle-bot}"
      GH_COMMITER_EMAIL: "${GH_COMMITER_EMAIL:-147276322+openswoole-bundle-bot@users.noreply.github.com}"
      GH_COMMITER_SIGNING_KEY: "${GH_COMMITER_SIGNING_KEY:-xxxx}"
      GH_COMMITER_PGP_PRIVATE_KEY: "${GH_COMMITER_PGP_PRIVATE_KEY:-xxxx}"
      GH_TOKEN: "${GH_TOKEN:-xxxxxxxx}"
      GH_RELEASE_DRAFT: "${GH_RELEASE_DRAFT:-false}"
      GH_RELEASE_PRERELEASE: "${GH_RELEASE_PRERELEASE:-false}"
    volumes:
      - "~/.gnupg:/root/.gnupg_host:r"
      - "./.git:/usr/src/app/.git:rw"
      - "./CHANGELOG.md:/usr/src/app/CHANGELOG.md:rw"

  cli:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-openswoole-bundle}-cli:${TAG:-local}"
    container_name: openswoole-bundle-cli
    build:
      context: .
      target: cli
      args:
        <<: *DEFAULT_BUILD_ARGS
    environment:
      DATABASE_HOST: 'db'
    ports:
      - 9501:9501

  composer:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-openswoole-bundle}-composer:${TAG:-local}"
    build:
      context: .
      target: composer
      args:
        <<: *DEFAULT_BUILD_ARGS
    environment:
      DATABASE_HOST: 'db'

  ci:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-openswoole-bundle}-ci:${TAG:-local}"
    build:
      context: .
      target: ci
      args:
        <<: *DEFAULT_BUILD_ARGS
    environment:
      DATABASE_HOST: 'db'

  coverage-xdebug:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-openswoole-bundle}-coverage-xdebug:${TAG:-local}"
    build:
      context: .
      target: CoverageXdebug
      args:
        <<: *DEFAULT_BUILD_ARGS
    environment:
      DATABASE_HOST: 'db'

  coverage-pcov:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-openswoole-bundle}-coverage-pcov:${TAG:-local}"
    build:
      context: .
      target: CoveragePcov
      args:
        <<: *DEFAULT_BUILD_ARGS
    environment:
      DATABASE_HOST: 'db'

  coverage-xdebug-feature-with-retry:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-openswoole-bundle}-coverage-xdebug:${TAG:-local}"
    entrypoint:
      - /bin/bash
    command:
      - tests/run-feature-tests-code-coverage.sh
    build:
      context: .
      target: CoverageXdebug
      args:
        <<: *DEFAULT_BUILD_ARGS
    environment:
      DATABASE_HOST: 'db'

  merge-code-coverage:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-openswoole-bundle}-merge-code-coverage:${MERGE_COVERAGE_TAG:-local}"
    command: merge-code-coverage
    build:
      context: .
      target: MergeCodeCoverage
      args:
        <<: *DEFAULT_BUILD_ARGS

  db:
    container_name: swoole-bundle-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
