parameters:
  swoole_bundle.coroutines_support.enabled: false
  swoole_bundle.coroutines_support.compile_processors: [ ]
  swoole_bundle.coroutines_support.stability_checkers: [ ]
  swoole_bundle.coroutines_support.max_service_instances: 100000
  swoole_bundle.cache_dir_name: !php/const 'K911\Swoole\Bridge\Symfony\Bundle\DependencyInjection\ContainerConstants::PARAM_CACHE_FOLDER'
  swoole_bundle.cache_dir: '%kernel.cache_dir%/%swoole_bundle.cache_dir_name%'
  swoole_bundle.service_proxy_cache_dir: '%swoole_bundle.cache_dir%/services'

services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  K911\Swoole\Component\AtomicCounter:
    factory: [ 'K911\Swoole\Component\AtomicCounter', 'fromZero' ]

  K911\Swoole\Common\System\System:
    factory: [ 'K911\Swoole\Common\System\System', 'create' ]

  K911\Swoole\Component\ExceptionArrayTransformer:

  K911\Swoole\Server\Middleware\MiddlewareInjector:

  K911\Swoole\Server\RequestHandler\ExceptionHandler\ExceptionHandlerInterface: ~

  K911\Swoole\Server\RequestHandler\ExceptionHandler\ProductionExceptionHandler:

  K911\Swoole\Server\RequestHandler\ExceptionHandler\JsonExceptionHandler:
    arguments:
        $exceptionArrayTransformer: '@K911\Swoole\Component\ExceptionArrayTransformer'
        $verbosity: ~

  K911\Swoole\Server\RequestHandler\ExceptionRequestHandler:
    arguments:
      $decorated: '@K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler'
      $exceptionHandler: '@K911\Swoole\Server\RequestHandler\ExceptionHandler\ExceptionHandlerInterface'

  K911\Swoole\Bridge\Symfony\HttpFoundation\SetRequestRuntimeConfiguration:
    tags:
      - { name: 'swoole_bundle.bootable_service', priority: -1000 }

  K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjectorInterface: '@K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjector'

  K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjector:
    arguments:
      $responseProcessor: '@response_processor.headers_and_cookies.streamed'

  K911\Swoole\Bridge\Symfony\HttpKernel\KernelPoolInterface:
    alias: K911\Swoole\Bridge\Symfony\HttpKernel\SimpleKernelPool

  K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactoryInterface:
    alias: K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactory

  K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactory:

  K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface:
    class: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessor

  K911\Swoole\Bridge\Symfony\HttpFoundation\NoOpStreamedResponseProcessor:
    decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
    decoration_priority: -100
    arguments:
      - '@K911\Swoole\Bridge\Symfony\HttpFoundation\NoOpStreamedResponseProcessor.inner'

  response_processor.headers_and_cookies.default:
    class: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor
    decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
    arguments:
      - '@response_processor.headers_and_cookies.default.inner'

  K911\Swoole\Bridge\Symfony\HttpFoundation\StreamedResponseProcessor:

  response_processor.headers_and_cookies.streamed:
    class: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseHeadersAndStatusProcessor
    decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\StreamedResponseProcessor
    arguments:
      - '@response_processor.headers_and_cookies.streamed.inner'

  K911\Swoole\Server\RequestHandler\RequestHandlerInterface:
    alias: K911\Swoole\Server\RequestHandler\ExceptionRequestHandler

  K911\Swoole\Bridge\Symfony\HttpKernel\SimpleKernelPool:
    arguments:
      $kernel: '@kernel'

  K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler:
    arguments:
      $kernelPool: '@K911\Swoole\Bridge\Symfony\HttpKernel\KernelPoolInterface'
      $requestFactory: '@K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactoryInterface'
      $processorInjector: '@K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInjectorInterface'
      $responseProcessor: '@K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface'
    tags:
      - { name: 'swoole_bundle.bootable_service' }

  K911\Swoole\Bridge\Symfony\HttpKernel\ContextReleasingHttpKernelRequestHandler:
    arguments:
      $decorated: '@K911\Swoole\Server\RequestHandler\RequestHandlerInterface'
      $coWrapper: '@K911\Swoole\Bridge\Symfony\Container\CoWrapper'

  K911\Swoole\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorageFactory:

  K911\Swoole\Server\RequestHandler\LimitedRequestHandler:
    arguments:
      $decorated: '@K911\Swoole\Server\RequestHandler\RequestHandlerInterface'
      $server: '@K911\Swoole\Server\HttpServer'
      $requestCounter: '@K911\Swoole\Component\AtomicCounter'
    tags:
      - { name: 'swoole_bundle.bootable_service' }

  K911\Swoole\Server\Runtime\CallableBootManagerFactory:

  K911\Swoole\Server\Session\SwooleTableStorage:
    factory: [ 'K911\Swoole\Server\Session\SwooleTableStorage', 'fromDefaults' ]

  K911\Swoole\Server\Session\StorageInterface:
    alias: K911\Swoole\Server\Session\SwooleTableStorage

  K911\Swoole\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorage:

  K911\Swoole\Server\Runtime\BootableInterface:
    alias: K911\Swoole\Server\Runtime\CallableBootManager

  K911\Swoole\Server\Runtime\CallableBootManager:
    factory: [ '@K911\Swoole\Server\Runtime\CallableBootManagerFactory', 'make' ]
    arguments: [ !tagged 'swoole_bundle.bootable_service' ]

  K911\Swoole\Server\HttpServer:
    arguments:
      $configuration: '@K911\Swoole\Server\HttpServerConfiguration'

  K911\Swoole\Server\WorkerHandler\WorkerStartHandlerInterface: '@K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerStartHandler'

  K911\Swoole\Server\WorkerHandler\WorkerStopHandlerInterface: '@K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerStopHandler'

  K911\Swoole\Server\WorkerHandler\WorkerErrorHandlerInterface: '@K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerErrorHandler'

  K911\Swoole\Server\WorkerHandler\WorkerExitHandlerInterface: '@K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerExitHandler'

  K911\Swoole\Server\LifecycleHandler\ServerStartHandlerInterface: '@K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingServerStartHandler'

  K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerStartHandler:
    arguments:
      $eventDispatcher: '@event_dispatcher'

  K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerStopHandler:
    arguments:
      $eventDispatcher: '@event_dispatcher'

  K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerExitHandler:
    arguments:
      $eventDispatcher: '@event_dispatcher'

  K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingWorkerErrorHandler:
    arguments:
      $eventDispatcher: '@event_dispatcher'

  K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingServerStartHandler:
    arguments:
      $eventDispatcher: '@event_dispatcher'

  K911\Swoole\Server\LifecycleHandler\ServerShutdownHandlerInterface:
    class: K911\Swoole\Server\LifecycleHandler\NoOpServerShutdownHandler

  K911\Swoole\Server\LifecycleHandler\ServerManagerStartHandlerInterface:
    class: K911\Swoole\Server\LifecycleHandler\NoOpServerManagerStartHandler

  K911\Swoole\Server\LifecycleHandler\ServerManagerStopHandlerInterface:
    class: K911\Swoole\Server\LifecycleHandler\NoOpServerManagerStopHandler

  K911\Swoole\Server\TaskHandler\TaskHandlerInterface:
    class: K911\Swoole\Server\TaskHandler\NoOpTaskHandler

  K911\Swoole\Server\TaskHandler\TaskFinishedHandlerInterface:
    class: K911\Swoole\Server\TaskHandler\NoOpTaskFinishedHandler

  K911\Swoole\Bridge\Symfony\Messenger\ExceptionLoggingTransportHandler:
    arguments:
      $decorated: ~
      $logger: '@logger'
    tags:
      - { name: monolog.logger, channel: swoole }

  K911\Swoole\Bridge\Symfony\Messenger\ServiceResettingTransportHandler:
    arguments:
      $decorated: ~
      $resetter: '@services_resetter'

  K911\Swoole\Server\Api\ApiServerClientFactory:
    arguments:
      $sockets: '@K911\Swoole\Server\Config\Sockets'

  K911\Swoole\Server\Api\ApiServerClient:
    factory: ['@K911\Swoole\Server\Api\ApiServerClientFactory', 'newClient']

  K911\Swoole\Server\Api\ApiServerInterface:
    alias: K911\Swoole\Server\Api\ApiServer

  K911\Swoole\Server\Api\ApiServer:
    arguments:
      $server: '@K911\Swoole\Server\HttpServer'
      $serverConfiguration: '@K911\Swoole\Server\HttpServerConfiguration'

  #  Could be helpful for projects that uses/have included proxy-manager
  #        lazy: true
  #        tags:
  #            - { name: proxy, interface: K911\Swoole\Server\Api\ApiServerInterface }

  K911\Swoole\Server\Config\Sockets:

  K911\Swoole\Server\HttpServerConfiguration:

  K911\Swoole\Server\Configurator\WithHttpServerConfiguration:
    arguments:
      $configuration: '@K911\Swoole\Server\HttpServerConfiguration'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithServerShutdownHandler:
    arguments:
      $handler: '@K911\Swoole\Server\LifecycleHandler\ServerShutdownHandlerInterface'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithServerManagerStartHandler:
    arguments:
      $handler: '@K911\Swoole\Server\LifecycleHandler\ServerManagerStartHandlerInterface'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithServerManagerStopHandler:
    arguments:
      $handler: '@K911\Swoole\Server\LifecycleHandler\ServerManagerStopHandlerInterface'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithWorkerStartHandler:
    arguments:
      $handler: '@K911\Swoole\Server\WorkerHandler\WorkerStartHandlerInterface'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithWorkerStopHandler:
    arguments:
      $handler: '@K911\Swoole\Server\WorkerHandler\WorkerStopHandlerInterface'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithWorkerErrorHandler:
    arguments:
      $handler: '@K911\Swoole\Server\WorkerHandler\WorkerErrorHandlerInterface'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithWorkerExitHandler:
    arguments:
      $handler: '@K911\Swoole\Server\WorkerHandler\WorkerExitHandlerInterface'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithTaskHandler:
    arguments:
      $handler: '@K911\Swoole\Server\TaskHandler\TaskHandlerInterface'
      $configuration: '@K911\Swoole\Server\HttpServerConfiguration'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\WithTaskFinishedHandler:
    arguments:
      $handler: '@K911\Swoole\Server\TaskHandler\TaskFinishedHandlerInterface'
      $configuration: '@K911\Swoole\Server\HttpServerConfiguration'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Configurator\CallableChainConfiguratorFactory:

  K911\Swoole\Server\Api\WithApiServerConfiguration:
    arguments:
      $sockets: '@K911\Swoole\Server\Config\Sockets'
      $requestHandler: '@swoole_bundle.server.api_server.request_handler'
    tags:
        - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Server\Api\ApiServerRequestHandler:
    arguments:
      $apiServer: '@K911\Swoole\Server\Api\ApiServerInterface'

  swoole_bundle.server.api_server.request_handler:
    class: K911\Swoole\Server\RequestHandler\ExceptionRequestHandler
    arguments:
      $decorated: '@K911\Swoole\Server\Api\ApiServerRequestHandler'
      $exceptionHandler: '@K911\Swoole\Server\RequestHandler\ExceptionHandler\ExceptionHandlerInterface'

  swoole_bundle.server.http_server.configurator_collection:
    class: K911\Swoole\Component\GeneratedCollection
    arguments:
      $itemCollection: !tagged 'swoole_bundle.server_configurator'
      $items: []

  swoole_bundle.session.table_storage:
    alias: K911\Swoole\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorage

  swoole_bundle.session.table_storage_factory:
    alias: K911\Swoole\Bridge\Symfony\HttpFoundation\Session\SwooleSessionStorageFactory

  swoole_bundle.server.http_server.configurator.with_request_handler:
    class: K911\Swoole\Server\Configurator\WithRequestHandler
    arguments:
      $requestHandler: '@K911\Swoole\Server\RequestHandler\RequestHandlerInterface'

  swoole_bundle.server.http_server.configurator.with_limited_request_handler:
    class: K911\Swoole\Server\Configurator\WithRequestHandler
    arguments:
      $requestHandler: '@K911\Swoole\Server\RequestHandler\LimitedRequestHandler'

  swoole_bundle.server.http_server.configurator.default_handler:
    class: K911\Swoole\Server\Configurator\WithServerStartHandler
    arguments:
      $handler: '@K911\Swoole\Bridge\Symfony\Bundle\EventDispatcher\EventDispatchingServerStartHandler'
      $configuration: '@K911\Swoole\Server\HttpServerConfiguration'
    tags:
      - { name: 'swoole_bundle.server_configurator' }

  K911\Swoole\Bridge\Symfony\Container\Proxy\ProxyDirectoryHandler:
    arguments:
      $fileSystem: '@swoole_bundle.filesystem'
      $proxyDir: '%swoole_bundle.service_proxy_cache_dir%'

  K911\Swoole\Bridge\Symfony\Container\Proxy\FileLocatorFactory:
    arguments:
      $directoryHandler: '@K911\Swoole\Bridge\Symfony\Container\Proxy\ProxyDirectoryHandler'

  swoole_bundle.service_pool.locking:
    class: K911\Swoole\Component\Locking\Channel\ChannelMutexFactory

  swoole_bundle.unmanaged_factory_first_time.locking:
    class: K911\Swoole\Component\Locking\FirstTimeOnly\FirstTimeOnlyMutexFactory
    arguments:
      $wrapped: '@swoole_bundle.service_pool.locking'

  K911\Swoole\Bridge\Symfony\Container\Proxy\Instantiator:
    arguments:
      $proxyGenerator: '@K911\Swoole\Bridge\Symfony\Container\Proxy\Generator'

  K911\Swoole\Bridge\Symfony\Container\Proxy\UnmanagedFactoryInstantiator:
    arguments:
      $proxyFactory: '@swoole_bundle.unmanaged_factory_proxy_factory'
      $instantiator: '@K911\Swoole\Bridge\Symfony\Container\Proxy\Instantiator'
      $servicePoolContainer: '@K911\Swoole\Bridge\Symfony\Container\ServicePool\ServicePoolContainer'
      $limitLocking: '@swoole_bundle.service_pool.locking'
      $newInstanceLocking: '@swoole_bundle.unmanaged_factory_first_time.locking'

  swoole_bundle.filesystem:
    class: 'Symfony\Component\Filesystem\Filesystem'

  K911\Swoole\Bridge\Symfony\Container\Proxy\Generator:
    arguments:
      $configuration: '@swoole_bundle.service_proxy_configuration'

  swoole_bundle.unmanaged_factory_proxy_factory:
    class: 'ProxyManager\Factory\AccessInterceptorValueHolderFactory'
    arguments:
      $configuration: '@swoole_bundle.service_proxy_configuration'

  swoole_bundle.service_proxy_configuration:
    class: 'ProxyManager\Configuration'
    calls:
      - [ 'setGeneratorStrategy', [ '@swoole_bundle.repository_proxy_file_writer_generator' ] ]
      - [ 'setProxiesTargetDir', [ '%swoole_bundle.service_proxy_cache_dir%' ] ]

  swoole_bundle.repository_proxy_file_writer_generator:
    class: 'ProxyManager\GeneratorStrategy\FileWriterGeneratorStrategy'
    arguments:
      $fileLocator: '@swoole_bundle.repository_proxy_file_locator'

  swoole_bundle.repository_proxy_file_locator:
    class: 'ProxyManager\FileLocator\FileLocator'
    factory: ['@K911\Swoole\Bridge\Symfony\Container\Proxy\FileLocatorFactory', 'createFileLocator']
    arguments:
      $proxiesDirectory: '%swoole_bundle.service_proxy_cache_dir%'

  K911\Swoole\Bridge\Symfony\Container\CoWrapper:
    arguments:
      $servicePoolContainer: '@K911\Swoole\Bridge\Symfony\Container\ServicePool\ServicePoolContainer'

  K911\Swoole\Bridge\Symfony\Container\ServicePool\ServicePoolContainer:
    arguments:
      $pools: [ ]

  K911\Swoole\Bridge\Doctrine\ORM\EntityManagerStabilityChecker:
    tags: [ 'swoole_bundle.stability_checker' ]

  K911\Swoole\Bridge\Symfony\HttpKernel\CoroutineKernelPool:
    arguments:
      $kernel: '@kernel'

  K911\Swoole\Bridge\Symfony\Bundle\DependencyInjection\CompilerPass\StatefulServices\NonSharedSvcPoolConfigurator:
    arguments:
      $container: '@K911\Swoole\Bridge\Symfony\Container\ServicePool\ServicePoolContainer'

  K911\Swoole\Bridge\OpenSwoole\Metrics\MetricsProvider:
    tags:
      - { name: 'swoole_bundle.metrics_provider', extension: !php/const K911\Swoole\Common\System\Extension::OPENSWOOLE }

  K911\Swoole\Bridge\Swoole\Metrics\MetricsProvider:
    tags:
      - { name: 'swoole_bundle.metrics_provider', extension: !php/const K911\Swoole\Common\System\Extension::SWOOLE }

  K911\Swoole\Metrics\SystemMetricsProviderRegistry:
    arguments:
      $system: '@K911\Swoole\Common\System\System'
      $metricsProviders: !tagged_iterator { tag: 'swoole_bundle.metrics_provider', index_by: 'extension' }

  K911\Swoole\Metrics\MetricsProvider:
    factory: [ '@K911\Swoole\Metrics\SystemMetricsProviderRegistry', 'get' ]

  K911\Swoole\Bridge\OpenSwoole\OpenSwooleFactory:
    tags:
      - { name: 'swoole_bundle.swoole_adapter_factory', extension: !php/const K911\Swoole\Common\System\Extension::OPENSWOOLE }

  K911\Swoole\Bridge\Swoole\SwooleFactory:
    tags:
      - { name: 'swoole_bundle.swoole_adapter_factory', extension: !php/const K911\Swoole\Common\System\Extension::SWOOLE }

  K911\Swoole\Common\Adapter\SystemSwooleFactory:
    arguments:
      $system: '@K911\Swoole\Common\System\System'
      $adapterFactories: !tagged_iterator { tag: 'swoole_bundle.swoole_adapter_factory', index_by: 'extension' }

  K911\Swoole\Common\Adapter\Swoole:
    factory: [ '@K911\Swoole\Common\Adapter\SystemSwooleFactory', 'newInstance' ]
